name: build and deploy
on: push
env:
  IMAGE: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE }}
        containerfiles: https://gitlab.unige.ch/lettres/services/existdb/-/raw/main/Containerfile
    - if: github.ref == 'refs/heads/main'
      uses: redhat-actions/push-to-registry@v2
